services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      POSTGRES_USER: infosec_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: infosec_db
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: infosec_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: infosec_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:10.4.0
    container_name: student_grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  db_data:
  grafana_data: