"""Добавлено поле registration_date

Revision ID: 84efe5679c80
Revises: 8480554491ee
Create Date: 2024-12-17 03:20:26.482856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84efe5679c80'
down_revision = '8480554491ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###
