"""Добавлено поле deadline в модель Task

Revision ID: bff01e3b51c3
Revises: 
Create Date: 2024-12-21 18:21:14.164752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff01e3b51c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=False))
        batch_op.alter_column('manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('tasks_employee_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('tasks_manager_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['manager_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['employee_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_manager_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_manager_id_fkey', 'users', ['manager_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tasks_manager_id_fkey', 'users', ['manager_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('tasks_employee_id_fkey', 'users', ['employee_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
